spring:
 datasource:
  url: jdbc:mysql://localhost:3306/classicmodels
  username: ubuntu
  password: password
  
redis :
 cache : 
  downstream :
   enabled: true
   defaultt:
    host: from application dev
    port: 6379

message:
  from  : application_dev_yaml
