spring:
 datasource:
  url: jdbc:mysql://192.168.1.163:3306/classicmodels
#     username: ubuntu
#     password: password

redis :
 cache : 
  downstream :
   enabled: true
   host: from application dev
   port: 6379

message:
  from  : application_dev_yaml
