spring:
  jpa:
    show-sql : true
    
    hibernate:
      ddl-auto: update
      
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
        
  datasource:
    url: jdbc:mysql://localhost:3306/classicmodels
    username: ubuntu
    password: password
    
message:
  from  : user_config_yaml